### ISSUE TITLE
Inconcistency between column names in desired output and accepted output

### ISSUE THREAD

**Issue by plaes** [bootandy/window_funcs#1]
Although this is somewhat nitpicky, but currently, the column names in desired output are renamed - for example Q0 the desired output lists column names as name and total_weight, but accepts any names as long as the returned rows contain proper data.

Maybe there's a possibility to add "strict" mode where also the column names are checked?

(Also might be related to 50d9a3091e31f91dceb23a34d9fe426d85d050f9)

**Comment by bootandy** [comment]
I actually deliberately don't check the column names as I don't think people should have to worry about renaming the column.

That commit is unrelated - I added that as I saw too many people writing "select name, total_weight from cats" - I think they assumed total_weight was a column
