### ISSUE TITLE
Groupings question 6 misunderstanding

### ISSUE THREAD

**Issue by nireno** [bootandy/window_funcs#10]
In this question when you say they should show the second lightest cat's weight I'm thinking the following: 

| name   | breed      | weight | lightest_rank |
|--------|------------|--------|---------------|
| Puss   | Maine Coon | 5.1    | 1st           |
| Millie | Maine Coon | 5.4    | 2nd           |
| Misty  | Maine Coon | 5.7    | 3rd           |
| Smokey | Maine Coon | 6.1    | 4th           |

So the second lightest in my mind is 5.4 but your answer requires 5.7 which to me is the second heaviest cat. Am I just sleepy/misunderstanding?

**Comment by bootandy** [comment]
It seems you are correct. I need to remove the 'desc' on the order by.

Thanks for letting me know.

**Comment by nireno** [comment]
No problem. Thanks for taking the effort to build this app.

**Comment by bootandy** [comment]
https://github.com/bootandy/window_funcs/commit/8c5a3e5d350a0a31b4c1aab06f8e3aeb59abb7da
fixed
