### ISSUE TITLE
SQL code for runners table

### ISSUE THREAD

**Issue by femibyte** [bootandy/window_funcs#18]
Hi Andy, can you provide the DML and DDL for the runners table ? I'd like to try and play around with the examples you provide in my postgres database. Thanks for your site. It has been an awesome resource in teaching me the basics about windowing sql functions.

**Comment by bootandy** [comment]
This is the SQL I run, I just copy and paste and run: 

https://github.com/bootandy/window_funcs/blob/master/data/cats.txt
