### ISSUE TITLE
Question 6 is indeterminate

### ISSUE THREAD

**Issue by marksteward** [bootandy/window_funcs#2]
Question 6 requires ordering by rank but the result isn't ordered within those ranks. By chance, ordering by only the rank gives the correct result, but I don't think it's guaranteed to.

This works:
```
select 
dense_rank() over (order by age desc) r,
name, age
from cats
order by 1
```

This doesn't:
```
select 
dense_rank() over (order by age desc) r,
name, age
from cats
order by 1, 2
```

**Comment by am0d** [comment]
I had the same issue - the question states
```
Return: ranking, name, age
Order by: ranking, name 
```
but the required answer is missing the secondary sort (is not sorting by name).
